apiVersion: v1
kind: Secret
metadata:
  name: simple-node-app-secret
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-app
  labels:
    app: simple-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-node-app
  template:
    metadata:
      labels:
        app: simple-node-app
    spec:
      imagePullSecrets:
      - name: artifact-secret
      containers:
      - name: simple-node-app
        #image: node:latest # Atualize caso use um registro de container
        image: DOCKER_IMAGE
        imagePullSecrets: Always
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: simple-node-app-secret
            optional: false
        resources:
          requests:
            cpu: "25m"
            memory: "64Mi"
          limits:
            cpu: "50m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-node-app-service
spec:
  type: NodePort
  selector:
    app: simple-node-app
  ports:
  - protocol: TCP
    port: 5000 # Porta dentro do container
    targetPort: 5000 # Porta no container
    nodePort: 32500 # Porta exposta no nó
